import random

def get_my_jokes():
   
    jokes = [
"Why did the scarecrow win an award? Because he was outstanding in his field.",
"I told my computer I needed a break, and it said: 'No problem — I'll go to sleep.'",
"Why don't scientists trust atoms? Because they make up everything.",
"I asked the librarian if the library had books on paranoia. She whispered, 'They're right behind you.'",
"Why did the bicycle fall over? It was two-tired.",
"What do you call fake spaghetti? An impasta.",
"Why did the math book look sad? It had too many problems.",
"Why don't skeletons fight each other? They don't have the guts.",
"What do you call cheese that isn't yours? Nacho cheese.",
"How does a penguin build its house? Igloos it together.",
"Why did the tomato blush? It saw the salad dressing.",
"Why did the golfer bring two pairs of pants? In case he got a hole in one.",
"What do you call a fish with no eyes? Fsh.",
"Why did the cookie go to the doctor? It felt crummy.",
"What do you call a belt made of watches? A waist of time.",
"Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
"Why did the computer show up at work late? It had a hard drive.",
"Why did the coffee file a police report? It got mugged.",
"Why do bees have sticky hair? Because they use honeycombs.",
"Why can't you give Elsa a balloon? Because she will let it go.",
"How do you organize a space party? You planet.",
"What did one ocean say to the other ocean? Nothing — they just waved.",
"Why did the stadium get hot after the game? All of the fans left.",
"What do you call an alligator in a vest? An investigator.",
"Why are ghosts bad liars? Because you can see right through them.",
"What do you call a snowman with a six-pack? An abdominal snowman.",
"Why did the picture go to jail? Because it was framed.",
"What's orange and sounds like a parrot? A carrot.",
"Why did the M&M go to school? It wanted to be a Smartie.",
"Why can't your nose be 12 inches long? Because then it'd be a foot.",
"How do cows stay up to date with current events? They read the moos-paper.",
"Why don't eggs tell jokes? They'd crack each other up.",
"What do you call two birds in love? Tweethearts.",
"Why did the scarecrow become a successful neurosurgeon? (This one's a trick: he didn't — but he stayed outstanding in his field.)",
"What did the janitor say when he jumped out of the closet? 'Supplies!'",
"Why did the bicycle stand up by itself? It was two-tired.",
"What do you call a sleeping bull? A bulldozer.",
"Why was the math lecture so long? The professor kept going off on tangents.",
"Why did the grape stop in the middle of the road? It ran out of juice.",
"What did the stamp say to the envelope? Stick with me and we'll go places.",
"Why are frogs so happy? They eat whatever bugs them.",
"What kind of tree fits in your hand? A palm tree.",
"Why did the computer go to therapy? It had too many bytes of emotional baggage.",
"Why don't some couples go to the gym? Because some relationships don't work out.",
"Why did the baker go to therapy? He kneaded it.",
"What did one hat say to the other? You stay here — I'll go on ahead.",
"Why couldn't the pirate learn the alphabet? Because he kept getting lost at C.",
"What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
"Why did the chicken join a band? Because it had the drumsticks.",
"What do you call a cow with no legs? Ground beef.",
"Why did the orange stop? It ran out of juice.",
"How does a vampire start a letter? 'Tomb it may concern.'",
"What do you call an elephant that doesn't matter? An irrelephant.",
"Why was the broom late? It overswept.",
"Why did the student bring a ladder to school? Because he wanted to go to high school.",
"Why did the scarecrow keep getting promoted? He was outstanding in his field (yes, again — it's a classic).",
"Why do seagulls fly over the sea? Because if they flew over the bay they'd be bagels.",
"What did the zero say to the eight? Nice belt!",
"Why was the math book depressed? Too many problems.",
"How do you catch a squirrel? Climb a tree and act like a nut.",
"What do you call a group of musical whales? An orca-stra.",
"Why did the tomato turn red? Because it saw the salad dressing.",
"How does a train eat? It goes chew chew.",
"Why did the coffee go to school? To improve its grounds for learning.",
"Why are pirates called pirates? Because they arrrrr!",
"What's a skeleton's least favorite room? The living room.",
"Why did the belt go to jail? For holding up a pair of pants.",
"Why did the cookie cry? Because its mom was a wafer so long.",
"Why did the banana go to the doctor? It wasn't peeling well.",
"Why don't programmers like nature? Too many bugs.",
"Why did the programmer quit his job? Because he didn't get arrays.",
"Why do programmers prefer dark mode? Because light attracts bugs.",
"Why did the scarecrow get a promotion? Field expertise.",
"Why did the mobile phone go to school? It wanted better reception.",
"How do you fix a broken tuba? With a tuba glue.",
"Why did the skeleton cross the road? To get to the body shop.",
"What kind of music do mummies listen to? Wrap music.",
"Why are ghosts so bad at lying? Because they are transparent.",
"Why did the picture go to jail? It was framed (yes, again — short-term memory joke).",
"Why did the computer get cold? It left its Windows open.",
"What do you call a pig that knows karate? A pork chop.",
"Why did the man run around his bed? Because he was trying to catch up on his sleep.",
"Why did the vampire read the newspaper? He heard it had great circulation.",
"What did the grape say when it got stepped on? Nothing — but it let out a little wine.",
"Why do bicycles fall over? They are two-tired.",
"What do you call a dinosaur with an extensive vocabulary? A thesaurus (double feature!).",
"Why did the mushroom go to the party? Because he was a fungi.",
"Why don't scientists trust atoms? Because they make up everything (truth bomb).",
"Why did the scarecrow get invited to parties? He was outstanding in his field (triple threat).",
"What do you call a snowman in summer? A puddle.",
"Why did the physics teacher break up with the biology teacher? There was no chemistry.",
"Why did the cookie go to the doctor? It was feeling crummy (we're circling the classics).",
"What do you call an apology written in dots and dashes? Re-morse code.",
"Why did the golfer bring two shirts? In case he got a hole in one (backup fashion).",
"Why don't some fish play piano? Because you can't tuna fish.",
"Why did the scarecrow join the choir? To be outstanding in his field of notes.",
"What do you get from a pampered cow? Spoiled milk.",
"Why did the shell go to the party alone? It couldn't find a shell-mate.",
"Why are bananas never lonely? Because they hang out in bunches.",
"What do you call a nervous javelin thrower? Shakespeare in the park.",
"Why did the computer go to the doctor? Because it had a virus (classic computer medicine).",
"What did one volcano say to the other? I lava you.",
"Why did the calendar get promoted? It had a lot of dates.",
"Why did the student eat his homework? Because his teacher said it was a piece of cake (we said that, yes).",
"Why don't skeletons ever go trick-or-treating? They have no body to go with.",
"How does a snowman get around? By riding an 'icicle'.",
"What do you call a cow who just had a baby? De-calf-inated.",
"Why did the lion eat the tightrope walker? He wanted a well-balanced meal.",
"Why did the cake go to the doctor? It felt layer-ious.",
"How do you organize an outer space party? You planet (repeat-worthy).",
"What do you call a lazy kangaroo? A pouch potato.",
"Why did the hipster burn his tongue? He drank his coffee before it was cool.",
"Why did the bee get married? Because he found his honey.",
"Why do painters always fall for their models? They just can't resist a good palette.",
"Why did the golfer bring extra socks? In case he got a hole in one (socks edition)."
]
    joke=random.choice(jokes)
    return joke
def story():
    stories= [
    "He found a map in his grandfather’s attic. It led not to treasure, but to the place where he first learned courage.",
    "She drew a door on the wall and dreamed it open. When she woke up, the wall was gone.",
    "The boy could hear colors. When the world went silent, he painted it back.",
    "A storm took the village, but left one candle burning in the window — hers.",
    "He traded memories for wishes until he forgot what he wanted.",
    "The robot wrote love letters it could never send.",
    "She spent years chasing happiness, only to find it waiting at her front door.",
    "He built a boat from promises and sailed it across regret.",
    "The photograph changed every night — showing a life he never lived.",
    "She sang to the sea until it learned her name.",
    "The scientist discovered a new color — visible only to the brokenhearted.",
    "He counted stars until one counted back.",
    "She left a note in every library book: 'You are not alone.'",
    "The mirror lied to everyone except him.",
    "He opened a music box and heard his childhood laugh again.",
    "The painter’s final canvas was blank — because he’d finally seen enough.",
    "A lost cat returned wearing a collar that read, 'Thank you for everything.'",
    "She taught shadows to dance.",
    "He woke to find his dreams written on the ceiling in his own handwriting.",
    "The lighthouse stopped shining, but ships still found their way home.",
    "The city forgot her name, but the wind still whispered it.",
    "He walked through the fire and came out gold.",
    "The moon hid that night, tired of watching humanity cry.",
    "She sold her fear and bought silence.",
    "He met himself at the crossroads and both turned opposite ways.",
    "The paper plane never landed. Somewhere, it’s still flying.",
    "She carved her diary into the tree bark so the forest would remember.",
    "The old musician played one final note — and the rain stopped to listen.",
    "He forgave the world quietly, so no one could ruin it again.",
    "The doll blinked for the first time when the girl stopped believing.",
    "She found love in a voicemail she never sent.",
    "He kept a broken clock because it was right twice a day — unlike him.",
    "The train never arrived, but he stayed waiting. Some departures feel like purpose.",
    "She turned her heartbreak into origami cranes and watched them fly.",
    "The stranger at the café looked exactly like her in twenty years.",
    "He followed footprints in the snow that ended at his own door.",
    "The ocean returned her bottle — empty, but with salt that wasn’t seawater.",
    "She made peace with her past when she realized it never hated her.",
    "He woke to find his reflection missing — freedom, finally.",
    "The letters she mailed to heaven always came back marked 'address unknown.'",
    "He stopped chasing perfection when imperfection smiled back.",
    "She planted sunflowers in the cracks of a war zone.",
    "He wrote her name in binary so no one else could read his heart.",
    "The last candle flickered out, and the stars applauded.",
    "She met a boy who collected broken things — including her.",
    "He threw his fear into the sea. It washed back as courage.",
    "She walked barefoot through shattered glass — and grew flowers where she bled.",
    "He invented a machine that could erase pain. Then he erased the blueprint.",
    "The child wished for wings. In the morning, there were feathers on the pillow.",
    "She told lies so beautiful they became art.",
    "He chased sunsets until one chased him back.",
    "She bottled laughter and sold it for free.",
    "He carved poems into the sand, knowing the waves would finish them.",
    "The painter mixed tears into the paint — the art finally felt alive.",
    "She left footprints on the moon and forgot how to come home.",
    "He turned scars into constellations.",
    "The magician vanished, leaving only applause — and his hat crying softly.",
    "She rewrote the ending every night until it stopped hurting.",
    "He saw angels in traffic lights — green meant hope, red meant healing.",
    "She stitched pieces of cloud into a dress and called it forgiveness.",
    "He promised forever, but forever was busy that day.",
    "The storm passed, but her heart still thundered.",
    "He danced with silence until it started to hum.",
    "She poured her grief into the river — it came back as music.",
    "He found his name etched on a tombstone — under 'To Be Continued.'",
    "The bird sang only for her, then forgot how to stop.",
    "She wrote an entire novel on receipts and napkins.",
    "He counted every lie until he ran out of numbers.",
    "She built a clock that moved backward — it told the truth.",
    "He fell in love with a ghost who didn’t know she was dead.",
    "She caught dreams in a jar and let nightmares go free.",
    "He sculpted wind just to prove beauty didn’t need weight.",
    "She walked into a mirror and never came out — but her reflection did.",
    "He prayed to time — and time answered, 'Wait.'",
    "She whispered her secret into the earth. The next day, a flower bloomed.",
    "He invented light, then missed the dark.",
    "She danced on the edge of reason and called it faith.",
    "He met God in a traffic jam — and they both apologized.",
    "She sold her laughter for rent money, but people kept returning it.",
    "He found eternity in a three-second glance.",
    "She learned that silence can scream louder than thunder.",
    "He wrote a love song for gravity and fell for real.",
    "She built a city out of second chances.",
    "He painted doors on walls and dared people to believe.",
    "She tattooed truth on her skin so she’d never forget.",
    "He dreamed of wings and woke up mid-flight.",
    "She named every raindrop and ran out of names.",
    "He taught a stone to skip, and it never came down.",
    "She saw her future in a puddle — blurry, but bright.",
    "He gave up everything for peace — and got it.",
    "She caught lightning in her palms and called it love.",
    "He slept under broken stars that still remembered how to shine.",
    "She burned her diary and found warmth for the first time.",
    "He wrote his fears on balloons and let them go — one stayed.",
    "She played the piano until her tears harmonized.",
    "He chased echoes until he became one.",
    "She turned loneliness into language.",
    "He fell into a dream and decided not to climb out.",
    "She met happiness by accident — and pretended not to recognize it.",
    "He drew constellations that spelled her name.",
    "She left behind her shadow — it followed anyway.",
    "He opened a book and found himself reading aloud his own future."]
    story=random.choice(stories)
    return story


